"""CONTENT: course → course version → module → lesson → lesson block.

A course is the long-lived identity. Everything a learner sees hangs off a *version*, so editing never
changes what enrolled learners are studying. Modules, lessons and blocks carry a `lineage_id` that stays the
same when a version is copied into a new draft, which lets progress follow a lesson across versions later."""
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..db import Base, Timestamps, id_column, new_id, utcnow
from ..enums import CourseStatus, LessonStatus, VersionStatus, Visibility
from .common import JSONType, one_of


class Course(Timestamps, Base):
    __tablename__ = "courses"
    __table_args__ = (one_of("status", list(CourseStatus)), one_of("visibility", list(Visibility)))

    id: Mapped[str] = id_column("crs")
    organization_id: Mapped[str] = mapped_column(ForeignKey("organizations.id", ondelete="RESTRICT"), index=True)
    created_by: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    updated_by: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    title: Mapped[str] = mapped_column(String(200), index=True)
    description: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String(20), default=CourseStatus.DRAFT)
    visibility: Mapped[str] = mapped_column(String(20), default=Visibility.PUBLIC)
    current_draft_version_id: Mapped[str | None] = mapped_column(
        ForeignKey("course_versions.id", ondelete="SET NULL", use_alter=True))
    current_published_version_id: Mapped[str | None] = mapped_column(
        ForeignKey("course_versions.id", ondelete="SET NULL", use_alter=True))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class CourseVersion(Base):
    __tablename__ = "course_versions"
    __table_args__ = (UniqueConstraint("course_id", "version_number"), one_of("status", list(VersionStatus)))

    id: Mapped[str] = id_column("ver")
    course_id: Mapped[str] = mapped_column(ForeignKey("courses.id", ondelete="CASCADE"), index=True)
    version_number: Mapped[int] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(20), default=VersionStatus.DRAFT)
    based_on_version_id: Mapped[str | None] = mapped_column(ForeignKey("course_versions.id", ondelete="SET NULL"))
    created_by: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    published_by: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))

    modules: Mapped[list["Module"]] = relationship(order_by="Module.position", cascade="all, delete-orphan")


class Module(Timestamps, Base):
    __tablename__ = "modules"

    id: Mapped[str] = id_column("mod")
    lineage_id: Mapped[str] = mapped_column(String(40), default=new_id("mln"), index=True)
    course_version_id: Mapped[str] = mapped_column(ForeignKey("course_versions.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(Text, default="")
    position: Mapped[int] = mapped_column(Integer, default=0)

    lessons: Mapped[list["Lesson"]] = relationship(order_by="Lesson.position", cascade="all, delete-orphan")


class Lesson(Timestamps, Base):
    __tablename__ = "lessons"
    __table_args__ = (one_of("status", list(LessonStatus)),)

    id: Mapped[str] = id_column("les")
    lineage_id: Mapped[str] = mapped_column(String(40), default=new_id("lln"), index=True)
    module_id: Mapped[str] = mapped_column(ForeignKey("modules.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(Text, default="")
    position: Mapped[int] = mapped_column(Integer, default=0)
    estimated_minutes: Mapped[int] = mapped_column(Integer, default=5)
    status: Mapped[str] = mapped_column(String(20), default=LessonStatus.DRAFT)

    blocks: Mapped[list["LessonBlock"]] = relationship(order_by="LessonBlock.position", cascade="all, delete-orphan")


class LessonBlock(Timestamps, Base):
    """A typed piece of a lesson. `config` is validated against the block registry (services/blocks.py),
    so a block written by a person today and one generated by the engine later share one contract."""
    __tablename__ = "lesson_blocks"

    id: Mapped[str] = id_column("blk")
    lineage_id: Mapped[str] = mapped_column(String(40), default=new_id("bln"), index=True)
    lesson_id: Mapped[str] = mapped_column(ForeignKey("lessons.id", ondelete="CASCADE"), index=True)
    block_type: Mapped[str] = mapped_column(String(40))
    position: Mapped[int] = mapped_column(Integer, default=0)
    config: Mapped[dict] = mapped_column("config_json", JSONType, default=dict)
    # provenance, filled in once generation exists (Wave 2+)
    generated_by: Mapped[str | None] = mapped_column(String(40))
    model: Mapped[str | None] = mapped_column(String(80))
    prompt_version: Mapped[str | None] = mapped_column(String(40))
    pipeline_version: Mapped[str | None] = mapped_column(String(40))
